### ISSUE TITLE
Fix up sidebar responsiveness

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-frontend#24]
Right now it looks shit if not on a desktop. The sidebar menu needs to be responsive, and things can't just slide on top of each other on smaller screens.

<img width="932" alt="screen shot 2018-11-11 at 9 17 23 am" src="https://user-images.githubusercontent.com/2975660/48306746-a91c7300-e592-11e8-82ce-61031b57dfd1.png">

**Comment by shuttle1987** [comment]
Fixed by PR #67
