### ISSUE TITLE
Check corpus creation

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-frontend#44]
Might be that when you create a corpus, it doesn't put things in the right partitions. Need to check this and see if it's a bug here or upstream.

**Comment by shuttle1987** [comment]
I'm going to guess it's this issue https://github.com/persephone-tools/persephone-web-API/issues/58 if that's the case please add the label indicating API work is required.

**Comment by aapeliv** [comment]
I'll need to check this. Just a note for me not to forget.

**Comment by aapeliv** [comment]
Closing as this is a bug upstream: persephone-tools/persephone-web-API#161
